# Use this for things like armor and tools (unstackable items).
items:
  - CHAINMAIL_HELMET
  - CHAINMAIL_CHESTPLATE
  - CHAINMAIL_LEGGINGS
  - CHAINMAIL_BOOTS
  - IRON_SWORD
  - IRON_PICKAXE

# Use this for things like food and blocks (stackable items).
consumables:
  BREAD: 10